//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilesenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bilesenler()
        {
            this.BilesenSaclari = new HashSet<BilesenSaclari>();
            this.UrunBilesenleri = new HashSet<UrunBilesenleri>();
            this.BilesenKProfilleri = new HashSet<BilesenKProfilleri>();
        }
    
        public int BilesenID { get; set; }
        public string BilesenAdi { get; set; }
        public Nullable<int> BilesenAdet { get; set; }
        public string BilesenBirimi { get; set; }
        public Nullable<decimal> BilesenAgirlik { get; set; }
        public Nullable<decimal> BilesenBirimFiyati { get; set; }
        public Nullable<int> KaydedenID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilesenSaclari> BilesenSaclari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunBilesenleri> UrunBilesenleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilesenKProfilleri> BilesenKProfilleri { get; set; }
    }
}
