//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilesenSaclari
    {
        public int BilesenSaclariID { get; set; }
        public Nullable<int> BilesenID { get; set; }
        public Nullable<int> SacID { get; set; }
        public Nullable<decimal> AgirlikTutari { get; set; }
        public Nullable<decimal> SacAgirlik { get; set; }
    
        public virtual Bilesenler Bilesenler { get; set; }
        public virtual Saclar Saclar { get; set; }
    }
}
