//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkBilesenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EkBilesenler()
        {
            this.UrunEkBilesenleri = new HashSet<UrunEkBilesenleri>();
        }
    
        public int EkBilesenID { get; set; }
        public string EkBilesenAdi { get; set; }
        public string EkBilesenBirimi { get; set; }
        public Nullable<int> EkBilesenAdet { get; set; }
        public Nullable<decimal> EkBilesenAgirlik { get; set; }
        public Nullable<decimal> EkBilesenAdetFiyati { get; set; }
        public Nullable<int> KaydedenID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunEkBilesenleri> UrunEkBilesenleri { get; set; }
    }
}
