//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkIslemMaliyeti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EkIslemMaliyeti()
        {
            this.UrunEkIslemMaliyetleri = new HashSet<UrunEkIslemMaliyetleri>();
        }
    
        public int EkIslemMaliyetiID { get; set; }
        public string EkIslemMaliyetiAdi { get; set; }
        public Nullable<decimal> EkIslemMaliyetiUzunluk { get; set; }
        public Nullable<decimal> EkIslemMaliyetiFiyati { get; set; }
        public Nullable<int> KaydedenID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunEkIslemMaliyetleri> UrunEkIslemMaliyetleri { get; set; }
    }
}
