//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormYetkileri
    {
        public int FormYetkileriID { get; set; }
        public string FormAdi { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<bool> Ac { get; set; }
        public Nullable<bool> Ekle { get; set; }
        public Nullable<bool> Guncelle { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<int> KaydedenID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
