//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KutuProfiller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KutuProfiller()
        {
            this.BilesenKProfilleri = new HashSet<BilesenKProfilleri>();
        }
    
        public int KProfilID { get; set; }
        public string KProfilAdi { get; set; }
        public string KProfilBirimi { get; set; }
        public Nullable<decimal> KProfilBirimFiyati { get; set; }
        public Nullable<decimal> KProfilAgirlik { get; set; }
        public Nullable<decimal> KProfilUzunluk { get; set; }
        public Nullable<int> KaydedenID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilesenKProfilleri> BilesenKProfilleri { get; set; }
    }
}
