//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaliyetEkleri
    {
        public int MaliyetEkleriID { get; set; }
        public Nullable<int> MaliyetID { get; set; }
        public Nullable<int> EkMaliyetID { get; set; }
        public Nullable<decimal> MaliyetFiyati { get; set; }
    
        public virtual EkMaliyetler EkMaliyetler { get; set; }
        public virtual Maliyetler Maliyetler { get; set; }
    }
}
