//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaliyetDetayi
    {
        public int MaliyetDetayiID { get; set; }
        public Nullable<int> MaliyetID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public string MaliyetBirimi { get; set; }
        public Nullable<decimal> BirimAgirlik { get; set; }
        public Nullable<decimal> BirimFiyati { get; set; }
        public Nullable<int> UrunMiktari { get; set; }
        public Nullable<decimal> ToplamAgirlik { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
    
        public virtual Maliyetler Maliyetler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
