//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maliyetler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maliyetler()
        {
            this.MaliyetDetayi = new HashSet<MaliyetDetayi>();
            this.MaliyetEkleri = new HashSet<MaliyetEkleri>();
        }
    
        public int MaliyetID { get; set; }
        public Nullable<decimal> IlkTutar { get; set; }
        public Nullable<decimal> GenelToplamAgirlik { get; set; }
        public Nullable<decimal> GenelToplamTutar { get; set; }
        public Nullable<int> KaydedenID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaliyetDetayi> MaliyetDetayi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaliyetEkleri> MaliyetEkleri { get; set; }
    }
}
