//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saclar()
        {
            this.BilesenSaclari = new HashSet<BilesenSaclari>();
        }
    
        public int SacID { get; set; }
        public string SacAdi { get; set; }
        public string SacBirimi { get; set; }
        public Nullable<decimal> SacBirimFiyati { get; set; }
        public Nullable<decimal> SacAgirlik { get; set; }
        public Nullable<int> KaydedenID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilesenSaclari> BilesenSaclari { get; set; }
    }
}
