//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiparisTakipEntities : DbContext
    {
        public SiparisTakipEntities()
            : base("name=SiparisTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilesenler> Bilesenler { get; set; }
        public virtual DbSet<BilesenSaclari> BilesenSaclari { get; set; }
        public virtual DbSet<EkBilesenler> EkBilesenler { get; set; }
        public virtual DbSet<EkIslemMaliyeti> EkIslemMaliyeti { get; set; }
        public virtual DbSet<EkMaliyetler> EkMaliyetler { get; set; }
        public virtual DbSet<KutuProfiller> KutuProfiller { get; set; }
        public virtual DbSet<MaliyetDetayi> MaliyetDetayi { get; set; }
        public virtual DbSet<MaliyetEkleri> MaliyetEkleri { get; set; }
        public virtual DbSet<Maliyetler> Maliyetler { get; set; }
        public virtual DbSet<Saclar> Saclar { get; set; }
        public virtual DbSet<UrunBilesenleri> UrunBilesenleri { get; set; }
        public virtual DbSet<UrunEkBilesenleri> UrunEkBilesenleri { get; set; }
        public virtual DbSet<UrunEkIslemMaliyetleri> UrunEkIslemMaliyetleri { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<KullaniciSonGirisTarihi> KullaniciSonGirisTarihi { get; set; }
        public virtual DbSet<FormYetkileri> FormYetkileri { get; set; }
        public virtual DbSet<BilesenKProfilleri> BilesenKProfilleri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
