//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunEkBilesenleri
    {
        public int UrunEkBilesenleriID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> EkBilesenID { get; set; }
        public Nullable<int> UrunEkBilesenleriAdet { get; set; }
        public Nullable<decimal> UrunEkBilesenleriAdetAgirlik { get; set; }
        public Nullable<decimal> UrunEkBilesenleriAdetTutari { get; set; }
    
        public virtual EkBilesenler EkBilesenler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
