//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunEkIslemMaliyetleri
    {
        public int UrunEkIslemMaliyetleriID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> EkIslemMaliyetiID { get; set; }
        public Nullable<decimal> UrunEkIslemMaliyetleriFiyati { get; set; }
        public Nullable<decimal> UrunEkIslemMaliyetleriUzunluk { get; set; }
    
        public virtual EkIslemMaliyeti EkIslemMaliyeti { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
